### ISSUE TITLE
Greate Plugin. Exactly what I need.

### ISSUE THREAD

**Issue by writeosahon** [rodrigo-martinezd/cordova-dialog-gps#10]
@rodrigo-martinezd  thanks for this plugin. It's exactly what I need for my project.
Please keep up the good work on the plugin.
When do you plan to release the feature of turning gps on and off directly from the dialog? You have marked that feature for release in version 0.1.0. Please when will that be released? With that feature, plugin will be perfect!!

Thanks

**Comment by rodrigo-md** [comment]
Thanks , I thought to release in mid-August but of course could be extended as I test it in different versions of Android .

**Comment by writeosahon** [comment]
Nice. That time frame is ok by me.
