### ISSUE TITLE
Is Plugin Still Being Developed

### ISSUE THREAD

**Issue by writeosahon** [rodrigo-martinezd/cordova-dialog-gps#12]
Hello @rodrigo-martinezd . Please, i'll like to know if you are still working on improvement features for this plugin?
The plugin is nice and I intend to use it for my project, that's why I starred it.
But I need to know if you are still working on improving the features of the plugin. I am very interested in the Swich-in-view feature. Are you working on this?

Thanks for the plugin

**Comment by rodrigo-md** [comment]
Hello , 

First I want to apologize for not responding sooner , I meet a lot of work and had forgotten to answer. 

I'm  still developing the plugin. I haven't upload changes yet but i have locally. Even unfinished, I can assure that the functionality you're hoping will not be applicable to all models. works in certain versions of Android  4 and earlier to 2.3. In the next week I'll upload the next version of the plugin.

Regards.

**Comment by writeosahon** [comment]
Thanks for the reply.
No problem if the feature does not work for all Android versions. 
I can use the current version of the plugin. It's a very great plugin.
Please make sure that your JavaScript methods for the new version of the plugin  are backward compatible with this current version.

Your plugin is very great and it provides a very necessary functionality for Cordova developers. Please submit the plugin details to plugins.telerik.com . Submission is free and more people will get to know about your work.

Regards.

Osahon Okungbowa
Sent from my Windows Phone

-----Original Message-----

**Comment by rodrigo-md** [comment]
Thanks for the advice, i'll publish in the next version.

Regards

2015-08-30 10:57 GMT-03:00 Osahon Okungbowa notifications@github.com:

> Thanks for the reply.
> No problem if the feature does not work for all Android versions.
> I can use the current version of the plugin. It's a very great plugin.
> Please make sure that your JavaScript methods for the new version of the
> plugin are backward compatible with this current version.
> 
> Your plugin is very great and it provides a very necessary functionality
> for Cordova developers. Please submit the plugin details to
> plugins.telerik.com . Submission is free and more people will get to know
> about your work.
> 
> Regards.
> 
> Osahon Okungbowa
> Sent from my Windows Phone
> 
> -----Original Message-----
> From: "rodrigo-martinezd" notifications@github.com
> Sent: ‎30/‎08/‎2015 06:41 AM
> To: "rodrigo-martinezd/cordova-dialog-gps" <
> cordova-dialog-gps@noreply.github.com>
> Cc: "Osahon Okungbowa" writeosahon@yahoo.co.uk
> Subject: Re: [cordova-dialog-gps] Is Plugin Still Being Developed (#12)
> 
> Hello ,
> First I want to apologize for not responding sooner , I meet a lot of work
> and had forgotten to answer.
> I'm still developing the plugin. I haven't upload changes yet but i have
> locally. Even unfinished, I can assure that the functionality you're hoping
> will not be applicable to all models. works in certain versions of Android
> 4 and earlier to 2.3. In the next week I'll upload the next version of the
> plugin.
> Regards.
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rodrigo-martinezd/cordova-dialog-gps/issues/12#issuecomment-136139791
> .

## 

Rodrigo Martínez Díaz
Estudiante de Ing. Civil Informática
Universidad Técnica Santa María.
