### ISSUE TITLE
Does it work? 

### ISSUE THREAD

**Issue by SalavertVincent** [rodrigo-martinezd/cordova-dialog-gps#6]
Hi, you just made what i'm looking for! 
Is it working?

**Comment by rodrigo-md** [comment]
yes, is working . For now  accepts the same parameters as a dialog, title , message , array of buttons and one single callback . In the next releases i want to allow to change the state of GPS directly from the dialog and enable support for promises .

Please , if you use it and have a problem Help me fix opening an **issue** and explaining the problem.

**Comment by rodrigo-md** [comment]
I forgot to tell you, if the project is what you wanted and you served . Please gift a **star**, this serves so that the next people who come to the project  check that it was worked effectively to others.

**Comment by SalavertVincent** [comment]
Ok, i just finished to work, but tomorow i will try to use it then! 
If i finally make it work i will give you all the stars i can! =D

Have you a documentation more complete than this one? 

Thanks for your help.

**Comment by rodrigo-md** [comment]
Hi, I did yesterday some improvements and updating documentation . I hope this helps.

**Comment by SalavertVincent** [comment]
Hi,
Yes it help me, thank you a lot, u got the star ! ;)

De : rodrigo-martinezd [mailto:notifications@github.com]
Envoyé : vendredi 24 juillet 2015 18:11
À : rodrigo-martinezd/cordova-dialog-gps cordova-dialog-gps@noreply.github.com
Cc : SALAVERT Vincent Vincent.SALAVERT@supinfo.com
Objet : Re: [cordova-dialog-gps] Does it work? (#6)

Hi, I did yesterday some improvements and updating documentation . I hope this helps.
